// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace ShoppingCart.Client.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class CartResponse
    {
        /// <summary>
        /// Initializes a new instance of the CartResponse class.
        /// </summary>
        public CartResponse()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the CartResponse class.
        /// </summary>
        public CartResponse(System.Guid? cartId = default(System.Guid?), System.Guid? customerId = default(System.Guid?), double? totalPrice = default(double?), IList<CartItemResponse> items = default(IList<CartItemResponse>))
        {
            CartId = cartId;
            CustomerId = customerId;
            TotalPrice = totalPrice;
            Items = items;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "cartId")]
        public System.Guid? CartId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "customerId")]
        public System.Guid? CustomerId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "totalPrice")]
        public double? TotalPrice { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "items")]
        public IList<CartItemResponse> Items { get; set; }

    }
}
