// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace ShoppingCart.Client.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class RemoveItemRequest
    {
        /// <summary>
        /// Initializes a new instance of the RemoveItemRequest class.
        /// </summary>
        public RemoveItemRequest()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the RemoveItemRequest class.
        /// </summary>
        public RemoveItemRequest(string productName = default(string))
        {
            ProductName = productName;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "productName")]
        public string ProductName { get; set; }

    }
}
